### ISSUE TITLE
UI for “in drill” location tracking stage of drill event

### ISSUE THREAD

**Issue by kaff-oregonstate** [kaff-oregonstate/oregon-state-evacuation-app#20]
We want to develop the UI/UX that will be used when the drill is active. This UI should:

- [x] load when the drill is "started"
- [x] if location permissions are granted, should begin tracking the location
- [x] inform the participant as to whether or not their location is being tracked
- [x] display instructions from researchers on what to do (the scenario the participant has been assigned). For now this should be a hard-coded example
- [x] end the drill when they have reached their destination (or need to stop participation) (maybe a popup to confirm the action?)
- [x] when the drill is ended, stop location tracking if not yet stopped
- [x] when the drill is ended, navigate to the post-drill survey
